[control]
prefix = "huckel"
outdir = "./fcidump"
save_integrals = true
integral_format = "fcidump"

[system]
moltype = "1d"
bc = "periodic"
norb = 6
nelec = 6

[model]
hamiltonian = "Huckel"
basis = "spatial basis"
alpha = 1.0
beta = -2.0
u_onsite = 1.0